export {default as About} from './About'
export {default as Home} from './Home'
export {default as People} from './People'
export {default as NotFound} from './NotFound'
export {default as Person} from './Person'